# Cloud Build: build + push + deploy API & Compute (Gen2)
# Repo root: /cloudbuild.yaml

substitutions:
  _REGION: "us-central1"
  _AR_REPO: "goldmind"
  _SERVICE_API: "goldmind-api"
  _SERVICE_COMPUTE: "goldmind-compute"
  _API_DOMAIN: "https://api.fwvgoldmindai.com"
  _ENV: "prod"
  _USE_YFINANCE: "true"

options:
  logging: CLOUD_LOGGING_ONLY
  substitution_option: ALLOW_LOOSE

steps:
  # Build API image from ./api using api/Dockerfile (capital D)
  - name: gcr.io/cloud-builders/docker
    id: "Build API image"
    args:
      - build
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE_API}:$COMMIT_SHA
      - -f
      - ./api/Dockerfile
      - ./api

  # Build Compute image from ./compute using compute/Dockerfile
  - name: gcr.io/cloud-builders/docker
    id: "Build Compute image"
    args:
      - build
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE_COMPUTE}:$COMMIT_SHA
      - -f
      - ./compute/Dockerfile
      - ./compute

  # Push API image
  - name: gcr.io/cloud-builders/docker
    id: "Push API image"
    args:
      - push
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE_API}:$COMMIT_SHA

  # Push Compute image
  - name: gcr.io/cloud-builders/docker
    id: "Push Compute image"
    args:
      - push
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE_COMPUTE}:$COMMIT_SHA

  # Deploy API to Cloud Run (Gen2)
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: "Deploy API"
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_SERVICE_API}
      - --image=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE_API}:$COMMIT_SHA
      - --region=${_REGION}
      - --platform=managed
      - --allow-unauthenticated
      - --project=$PROJECT_ID
      - --quiet

  # Deploy Compute to Cloud Run (Gen2)
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: "Deploy Compute"
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_SERVICE_COMPUTE}
      - --image=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE_COMPUTE}:$COMMIT_SHA
      - --region=${_REGION}
      - --platform=managed
      - --project=$PROJECT_ID
      - --quiet
