# cloudbuild.yaml  (dual-service: api + compute, with smoke + summary)

substitutions:
  _REGION: us-central1
  _ARTIFACT_REPO: goldmind
  _SERVICE_API: goldmind-api
  _SERVICE_COMPUTE: goldmind-compute
  _API_DOMAIN: https://api.fwvgoldmindai.com
  _ENV: prod
  _USE_YFINANCE: "true"
  _STRICT_SMOKE: "true"

timeout: "1200s"

steps:
  - id: 01-auth-ar
    name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    entrypoint: bash
    args:
      - -c
      - >
        set -e;
        gcloud auth configure-docker ${_REGION}-docker.pkg.dev -q

  - id: 02-build-api
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - api/Dockerfile
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/${_SERVICE_API}:$SHORT_SHA
      - api

  - id: 03-build-compute
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - compute/Dockerfile
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/${_SERVICE_COMPUTE}:$SHORT_SHA
      - compute

  - id: 04-push-api
    name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/${_SERVICE_API}:$SHORT_SHA

  - id: 05-push-compute
    name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/${_SERVICE_COMPUTE}:$SHORT_SHA

  - id: 06-deploy-api
    name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    entrypoint: bash
    args:
      - -c
      - >
        set -euo pipefail;
        gcloud run deploy ${_SERVICE_API}
        --image ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/${_SERVICE_API}:$SHORT_SHA
        --region ${_REGION}
        --platform managed
        --allow-unauthenticated
        --update-env-vars ENV=${_ENV},API_DOMAIN=${_API_DOMAIN},USE_YFINANCE=${_USE_YFINANCE}
        --timeout=300 --concurrency=80 --min-instances=0 --max-instances=4

  - id: 07-deploy-compute
    name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    entrypoint: bash
    args:
      - -c
      - >
        set -euo pipefail;
        gcloud run deploy ${_SERVICE_COMPUTE}
        --image ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/${_SERVICE_COMPUTE}:$SHORT_SHA
        --region ${_REGION}
        --platform managed
        --no-allow-unauthenticated
        --update-env-vars ENV=${_ENV}
        --timeout=300 --concurrency=20 --min-instances=0 --max-instances=2

  - id: 08-smoke-api
    name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    entrypoint: bash
    args:
      - -c
      - |
        set -euo pipefail
        API="${_API_DOMAIN}"
        STRICT="${_STRICT_SMOKE}"
        if [ -z "${STRICT}" ]; then STRICT=true; fi
        echo "Smoke (API) against $API  STRICT=$STRICT"

        # Wait for cold start
        for i in $(seq 1 24); do
          if curl -fsS "${API}/health" >/dev/null; then echo "OK: /health"; break; fi
          echo "Waiting for API /health (attempt $i)..."; sleep 5
        done

        fail=0
        check() {
          url="$1"
          if curl -fsS "$url" >/dev/null; then
            echo "  ✅ $url"
          else
            code=$?
            echo "  ❌ $url (curl exit $code)"
            [ "$STRICT" = "true" ] && fail=1
          fi
        }

        # GET endpoints
        check "${API}/"
        check "${API}/api/summary"
        check "${API}/market/gold/series"
        check "${API}/v1/predict?symbol=XAUUSD"
        check "${API}/v1/bias?symbol=XAUUSD"
        check "${API}/v1/feature-importance"
        check "${API}/v1/bias/influence"
        check "${API}/v1/alerts"

        # POST endpoints
        curl -fsS -X POST "${API}/predict" -H "Content-Type: application/json" \
             -d '{"symbol":"XAUUSD","horizon":"1d","amount":1.0,"indicators":["sma","ema","rsi"]}' >/dev/null || { echo "  ❌ /predict"; [ "$STRICT" = "true" ] && fail=1; }
        curl -fsS -X POST "${API}/compute/predict" -H "Content-Type: application/json" \
             -d '{"symbol":"XAUUSD","horizon":"1d","amount":1.0}' >/dev/null || { echo "  ❌ /compute/predict"; [ "$STRICT" = "true" ] && fail=1; }

        [ $fail -eq 0 ] || { echo "Smoke tests failed"; exit 1; }

  - id: 09-smoke-compute
    name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    entrypoint: bash
    args:
      - -c
      - |
        set -euo pipefail
        URL=$(gcloud run services describe ${_SERVICE_COMPUTE} --region ${_REGION} --format="value(status.url)")
        echo "Compute URL: $URL"
        # Expect 401/403 for private service; treat as pass
        code=$(curl -s -o /dev/null -w '%{http_code}' "$URL/health" || echo 000)
        echo "Compute /health HTTP $code"
        if [ "$code" = "200" ] || [ "$code" = "401" ] || [ "$code" = "403" ]; then
          echo "Compute smoke OK"
        else
          echo "Compute smoke FAILED (code $code)"; exit 1
        fi

  - id: 10-summary
    name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    entrypoint: bash
    args:
      - -c
      - |
        set -e
        API_URL=$(gcloud run services describe ${_SERVICE_API} --region ${_REGION} --format="value(status.url)")
        COMP_URL=$(gcloud run services describe ${_SERVICE_COMPUTE} --region ${_REGION} --format="value(status.url)")
        echo "------------------------------"
        echo "Build ID: $BUILD_ID"
        echo "API image: ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/${_SERVICE_API}:$SHORT_SHA"
        echo "Compute image: ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/${_SERVICE_COMPUTE}:$SHORT_SHA"
        echo "API (Cloud Run):  $API_URL"
        echo "API (Domain):     ${_API_DOMAIN}"
        echo "Compute (Cloud Run): $COMP_URL"
        echo "------------------------------"

images:
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/${_SERVICE_API}:$SHORT_SHA
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/${_SERVICE_COMPUTE}:$SHORT_SHA
