# CI/CD: Build + Push + Deploy API & Compute (Cloud Run Gen2)
# - Structured logging (deploy-smoke, deploy-summary)
# - Parallel smoke tests (12 x 5s = 60s grace)
# - Final step prints both service URLs

substitutions:
  _REGION: "us-central1"
  _AR_REPO: "goldmind"
  _SERVICE_API: "goldmind-api"
  _SERVICE_COMPUTE: "goldmind-compute"
  _API_DOMAIN: "https://api.fwvgoldmindai.com"
  _ENV: "prod"
  _USE_YFINANCE: "true"

options:
  logging: CLOUD_LOGGING_ONLY
  substitution_option: ALLOW_LOOSE

steps:
  # -------------------------
  # Build
  # -------------------------
  - name: "gcr.io/cloud-builders/docker"
    id: "Build API image"
    args:
      - "build"
      - "-t"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE_API}:$COMMIT_SHA"
      - "-f"
      - "./api/Dockerfile"
      - "./api"

  - name: "gcr.io/cloud-builders/docker"
    id: "Build Compute image"
    args:
      - "build"
      - "-t"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE_COMPUTE}:$COMMIT_SHA"
      - "-f"
      - "./compute/Dockerfile"
      - "./compute"

  # -------------------------
  # Push
  # -------------------------
  - name: "gcr.io/cloud-builders/docker"
    id: "Push API image"
    args:
      - "push"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE_API}:$COMMIT_SHA"

  - name: "gcr.io/cloud-builders/docker"
    id: "Push Compute image"
    args:
      - "push"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE_COMPUTE}:$COMMIT_SHA"

  # -------------------------
  # Deploy
  # -------------------------
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: "Deploy API"
    entrypoint: "gcloud"
    args:
      - "run"
      - "deploy"
      - "${_SERVICE_API}"
      - "--image=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE_API}:$COMMIT_SHA"
      - "--region=${_REGION}"
      - "--platform=managed"
      - "--allow-unauthenticated"
      - "--project=$PROJECT_ID"
      - "--quiet"

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: "Deploy Compute"
    entrypoint: "gcloud"
    args:
      - "run"
      - "deploy"
      - "${_SERVICE_COMPUTE}"
      - "--image=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE_COMPUTE}:$COMMIT_SHA"
      - "--region=${_REGION}"
      - "--platform=managed"
      - "--project=$PROJECT_ID"
      - "--quiet"

  # -------------------------
  # Smoke test: API (parallel)
  # -------------------------
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: "Smoke Test API Health"
    waitFor: ["Deploy API"]
    entrypoint: "bash"
    args:
      - "-lc"
      - |
        set -euo pipefail
        api_url="${_API_DOMAIN}/health"
        ts="$(date -Iseconds)"
        echo "Smoke testing API at ${api_url} ..."
        for i in {1..12}; do
          resp="$(curl -sS -m 10 -w ' HTTP_STATUS:%{http_code}' "${api_url}" || true)"
          status="${resp##*HTTP_STATUS:}"
          body="${resp% HTTP_STATUS:*}"
          body_b64="$(printf '%s' "$body" | base64 | tr -d '\n')"
          if [[ "$status" == "200" ]]; then
            gcloud logging write deploy-smoke \
              "{\"service\":\"${_SERVICE_API}\",\"url\":\"${api_url}\",\"status\":${status},\"ok\":true,\"ts\":\"${ts}\",\"body_b64\":\"${body_b64}\"}" \
              --payload-type=json --severity=INFO
            echo "API health OK (200)."
            exit 0
          fi
          echo "Attempt ${i}/12: API not ready (status=${status}). Retrying in 5s..."
          sleep 5
        done
        gcloud logging write deploy-smoke \
          "{\"service\":\"${_SERVICE_API}\",\"url\":\"${api_url}\",\"status\":\"fail\",\"ok\":false,\"ts\":\"${ts}\"}" \
          --payload-type=json --severity=ERROR
        echo "API health FAILED after grace period."
        exit 1

  # -------------------------
  # Smoke test: Compute (parallel)
  # -------------------------
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: "Smoke Test Compute Health"
    waitFor: ["Deploy Compute"]
    entrypoint: "bash"
    args:
      - "-lc"
      - |
        set -euo pipefail
        compute_url="$(gcloud run services describe "${_SERVICE_COMPUTE}" --region "${_REGION}" --format 'value(status.url)')"
        health_url="${compute_url}/health"
        ts="$(date -Iseconds)"
        echo "Smoke testing Compute at ${health_url} ..."
        for i in {1..12}; do
          resp="$(curl -sS -m 10 -w ' HTTP_STATUS:%{http_code}' "${health_url}" || true)"
          status="${resp##*HTTP_STATUS:}"
          body="${resp% HTTP_STATUS:*}"
          body_b64="$(printf '%s' "$body" | base64 | tr -d '\n')"
          if [[ "$status" == "200" ]]; then
            gcloud logging write deploy-smoke \
              "{\"service\":\"${_SERVICE_COMPUTE}\",\"url\":\"${health_url}\",\"status\":${status},\"ok\":true,\"ts\":\"${ts}\",\"body_b64\":\"${body_b64}\"}" \
              --payload-type=json --severity=INFO
            echo "Compute health OK (200)."
            exit 0
          fi
          echo "Attempt ${i}/12: Compute not ready (status=${status}). Retrying in 5s..."
          sleep 5
        done
        gcloud logging write deploy-smoke \
          "{\"service\":\"${_SERVICE_COMPUTE}\",\"url\":\"${health_url}\",\"status\":\"fail\",\"ok\":false,\"ts\":\"${ts}\"}" \
          --payload-type=json --severity=ERROR
        echo "Compute health FAILED after grace period."
        exit 1

  # -------------------------
  # Final summary
  # -------------------------
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: "Summary: Print Service URLs"
    waitFor:
      - "Smoke Test API Health"
      - "Smoke Test Compute Health"
    entrypoint: "bash"
    args:
      - "-lc"
      - |
        set -euo pipefail
        api_url="$(gcloud run services describe "${_SERVICE_API}" --region "${_REGION}" --format 'value(status.url)')"
        compute_url="$(gcloud run services describe "${_SERVICE_COMPUTE}" --region "${_REGION}" --format 'value(status.url)')"
        echo "=== Deployment Summary ==="
        echo "API URL:     ${api_url}"
        echo "Compute URL: ${compute_url}"
        gcloud logging write deploy-summary \
          "{\"api\":\"${api_url}\",\"compute\":\"${compute_url}\",\"env\":\"${_ENV}\",\"ts\":\"$(date -Iseconds)\"}" \
          --payload-type=json --severity=INFO
