# Cloud Build: build + push + deploy API & Compute (Gen2)
# Place at repo root: /cloudbuild.yaml

substitutions:
  _REGION: "us-central1"
  _AR_REPO: "goldmind"
  _SERVICE_API: "goldmind-api"
  _SERVICE_COMPUTE: "goldmind-compute"
  _API_DOMAIN: "https://api.fwvgoldmindai.com"
  _ENV: "prod"
  _USE_YFINANCE: "true"

options:
  logging: CLOUD_LOGGING_ONLY
  substitution_option: ALLOW_LOOSE

steps:
  # Debug: print substitution values
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: "DEBUG: print substitutions"
    entrypoint: bash
    args:
      - -c
      - |
        set -euo pipefail
        echo "_REGION=${_REGION}"
        echo "_AR_REPO=${_AR_REPO}"
        echo "_SERVICE_API=${_SERVICE_API}"
        echo "_SERVICE_COMPUTE=${_SERVICE_COMPUTE}"
        echo "_API_DOMAIN=${_API_DOMAIN}"
        echo "_ENV=${_ENV}"
        echo "_USE_YFINANCE=${_USE_YFINANCE}"

  # Build API image
  - name: gcr.io/cloud-builders/docker
    id: "Build API image"
    args:
      - build
      - -t
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE_API}:$COMMIT_SHA"
      - ./api

  # Build Compute image
  - name: gcr.io/cloud-builders/docker
    id: "Build Compute image"
    args:
      - build
      - -t
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE_COMPUTE}:$COMMIT_SHA"
      - ./compute

  # Push API image
  - name: gcr.io/cloud-builders/docker
    id: "Push API image"
    args:
      - push
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE_API}:$COMMIT_SHA"

  # Push Compute image
  - name: gcr.io/cloud-builders/docker
    id: "Push Compute image"
    args:
      - push
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE_COMPUTE}:$COMMIT_SHA"

  # Deploy API to Cloud Run
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: "Deploy API"
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_SERVICE_API}
      - --image=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE_API}:$COMMIT_SHA
      - --region=${_REGION}
      - --platform=managed
      - --allow-unauthenticated
      - --set-env-vars=ENV=${_ENV},API_DOMAIN=${_API_DOMAIN}

  # Deploy Compute to Cloud Run
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: "Deploy Compute"
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_SERVICE_COMPUTE}
      - --image=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE_COMPUTE}:$COMMIT_SHA
      - --region=${_REGION}
      - --platform=managed
      - --set-env-vars=ENV=${_ENV},API_DOMAIN=${_API_DOMAIN}
