# cloudbuild.yaml – build + push + deploy API and Compute (identical settings)

substitutions:
  _REGION: us-central1
  _REPO: goldmind
  _API_SERVICE: goldmind-api
  _COMPUTE_SERVICE: goldmind-compute
  _PORT: "8000"
  _MIN_INSTANCES: "1"
  _MAX_INSTANCES: "5"
  _CONCURRENCY: "80"
  _TIMEOUT: "900"
  _USE_YFINANCE: "true"
  _ENV: "prod"
  _API_DOMAIN: "https://api.fwvgoldmindai.com"

options:
  logging: CLOUD_LOGGING_ONLY

images:
  - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_API_SERVICE}:$BUILD_ID"
  - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_COMPUTE_SERVICE}:$BUILD_ID"

steps:
  # Authenticate Docker to Artifact Registry
  - name: gcr.io/cloud-builders/gcloud
    id: "Auth docker"
    args: ["auth", "configure-docker", "${_REGION}-docker.pkg.dev"]

  # --- Build & Push API ---
  - name: gcr.io/cloud-builders/docker
    id: "Build API"
    args:
      [
        "build",
        "-t", "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_API_SERVICE}:$BUILD_ID",
        "-f", "api/Dockerfile",
        "api"
      ]

  - name: gcr.io/cloud-builders/docker
    id: "Push API"
    args:
      ["push", "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_API_SERVICE}:$BUILD_ID"]

  - name: gcr.io/cloud-builders/gcloud
    id: "Deploy API"
    args:
      [
        "run", "deploy", "${_API_SERVICE}",
        "--image", "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_API_SERVICE}:$BUILD_ID",
        "--region", "${_REGION}",
        "--platform", "managed",
        "--allow-unauthenticated",
        "--port", "${_PORT}",
        "--min-instances", "${_MIN_INSTANCES}",
        "--max-instances", "${_MAX_INSTANCES}",
        "--concurrency", "${_CONCURRENCY}",
        "--timeout", "${_TIMEOUT}",
        "--set-env-vars", "ENV=${_ENV},USE_YFINANCE=${_USE_YFINANCE},API_DOMAIN=${_API_DOMAIN}"
      ]

  # --- Build & Push Compute ---
  - name: gcr.io/cloud-builders/docker
    id: "Build Compute"
    args:
      [
        "build",
        "-t", "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_COMPUTE_SERVICE}:$BUILD_ID",
        "-f", "compute/Dockerfile",
        "compute"
      ]

  - name: gcr.io/cloud-builders/docker
    id: "Push Compute"
    args:
      ["push", "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_COMPUTE_SERVICE}:$BUILD_ID"]

  - name: gcr.io/cloud-builders/gcloud
    id: "Deploy Compute"
    args:
      [
        "run", "deploy", "${_COMPUTE_SERVICE}",
        "--image", "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_COMPUTE_SERVICE}:$BUILD_ID",
        "--region", "${_REGION}",
        "--platform", "managed",
        "--allow-unauthenticated",
        "--port", "${_PORT}",
        "--min-instances", "${_MIN_INSTANCES}",
        "--max-instances", "${_MAX_INSTANCES}",
        "--concurrency", "${_CONCURRENCY}",
        "--timeout", "${_TIMEOUT}",
        "--set-env-vars", "ENV=${_ENV},USE_YFINANCE=${_USE_YFINANCE}"
      ]
