# Cloud Build: build + push + deploy API & Compute (Gen2)
# Place at repo root: /cloudbuild.yaml

substitutions:
  _REGION: "us-central1"
  _AR_REPO: "goldmind"
  _SERVICE_API: "goldmind-api"
  _SERVICE_COMPUTE: "goldmind-compute"
  _API_DOMAIN: "https://api.fwvgoldmindai.com"
  _ENV: "prod"
  _USE_YFINANCE: "true"

options:
  logging: CLOUD_LOGGING_ONLY
  substitution_option: ALLOW_LOOSE

steps:
  # Build API image from ./api using api/Dockerfile
  - name: gcr.io/cloud-builders/docker
    id: "Build API image"
    args:
      - build
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE_API}:$COMMIT_SHA
      - -f
      - ./api/Dockerfile
      - ./api

  # Build Compute image from ./compute using compute/Dockerfile
  - name: gcr.io/cloud-builders/docker
    id: "Build Compute image"
    args:
      - build
