# CI/CD: Build + Push + Deploy API & Compute (Cloud Run Gen2)

substitutions:
  _REGION: "us-central1"
  _AR_REPO: "goldmind"
  _SERVICE_API: "goldmind-api"
  _SERVICE_COMPUTE: "goldmind-compute"
  _API_DOMAIN: "https://api.fwvgoldmindai.com"
  _ENV: "prod"
  _USE_YFINANCE: "true"

options:
  logging: CLOUD_LOGGING_ONLY
  substitution_option: ALLOW_LOOSE

steps:
  # --- Build ---
  - name: gcr.io/cloud-builders/docker
    id: Build API image
    args:
      - build
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE_API}:$COMMIT_SHA
      - -f
      - ./api/Dockerfile
      - ./api

  - name: gcr.io/cloud-builders/docker
    id: Build Compute image
    args:
      - build
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE_COMPUTE}:$COMMIT_SHA
      - -f
      - ./compute/Dockerfile
      - ./compute

  # --- Push ---
  - name: gcr.io/cloud-builders/docker
    id: Push API image
    args: [ "push", "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE_API}:$COMMIT_SHA" ]

  - name: gcr.io/cloud-builders/docker
    id: Push Compute image
    args: [ "push", "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE_COMPUTE}:$COMMIT_SHA" ]

  # --- Deploy (Cloud Run Gen2) ---
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: Deploy API
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_SERVICE_API}
      - --image=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE_API}:$COMMIT_SHA
      - --region=${_REGION}
      - --platform=managed
      - --allow-unauthenticated
      - --project=$PROJECT_ID
      - --quiet

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: Deploy Compute
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_SERVICE_COMPUTE}
      - --image=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE_COMPUTE}:$COMMIT_SHA
      - --region=${_REGION}
      - --platform=managed
      - --project=$PROJECT_ID
      - --quiet

# Optional: add a simple smoke test after deploy (uncomment + adjust URL/headers)
#  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
#    id: Smoke test
#    entrypoint: bash
#    args:
#      - -lc
#      - |
#        set -euo pipefail
#        curl -fsSL https://api.fwvgoldmindai.com/health
