# cloudbuild.yaml
# Build & deploy GoldMIND API to Cloud Run, then smoke-test and print a summary.

substitutions:
  # ---- You can override these in the trigger if you want ----
  _REGION: us-central1
  _SERVICE: goldmind-api
  # Image path in Artifact Registry (adjust repo name if yours differs)
  _IMAGE: us-central1-docker.pkg.dev/$PROJECT_ID/goldmind-api/api:${SHORT_SHA}

  # Optional URLs you were referencing—now valid custom subs (start with "_").
  # If you don’t need them, they won’t break the build.
  _API_URL: https://api.fwvgoldmindai.com
  _COMPUTE_URL: https://goldmind-api-884387776097.us-central1.run.app

options:
  # Allow unused/undefined custom substitutions without failing the build.
  substitutionOption: ALLOW_LOOSE
  machineType: E2_HIGHCPU_8
  logging: CLOUD_LOGGING_ONLY

timeout: "1200s"

steps:
  # 1) Configure Docker to push to Artifact Registry
  - id: "auth: configure docker for AR"
    name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    entrypoint: bash
    args:
      - -c
      - |
        gcloud auth configure-docker $(echo "$_IMAGE" | awk -F/ '{print $1}') -q

  # 2) Build the image (Dockerfile path: api/Dockerfile)
  - id: "build: docker image"
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - --file=api/Dockerfile
      - --tag=$_IMAGE
      - .

  # 3) Push the image
  - id: "push: artifact registry"
    name: gcr.io/cloud-builders/docker
    args: ["push", "$_IMAGE"]

  # 4) Deploy to Cloud Run (keeps existing env vars unless you --set-env-vars here)
  - id: "deploy: cloud run"
    name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    entrypoint: bash
    args:
      - -c
      - |
        gcloud run deploy "$_SERVICE" \
          --region "$_REGION" \
          --platform managed \
          --image "$_IMAGE" \
          --allow-unauthenticated
        # Capture the live URL for smoke tests
        URL="$(gcloud run services describe "$_SERVICE" --region "$_REGION" --format='value(status.url)')"
        echo "SERVICE_URL=${URL}" > /workspace/deploy.env
        echo "IMAGE=$_IMAGE" >> /workspace/deploy.env

  # 5) Wait for rollout and smoke test /health
  - id: "test: /health"
    name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    entrypoint: bash
    args:
      - -c
      - |
        set -euo pipefail
        source /workspace/deploy.env
        echo "Waiting for service to become ready..."
        # Simple retry loop
        for i in {1..20}; do
          if curl -fsS "${SERVICE_URL}/health" >/dev/null 2>&1; then
            echo "Health check OK"
            exit 0
          fi
          sleep 5
        done
        echo "Health check FAILED"
        curl -i "${SERVICE_URL}/health" || true
        exit 1

  # 6) Summary
  - id: "summary"
    name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    entrypoint: bash
    args:
      - -c
      - |
        source /workspace/deploy.env
        echo "--------------------------------------------------"
        echo " GoldMIND API – Deploy Summary"
        echo " Project:     ${PROJECT_ID}"
        echo " Region:      ${_REGION}"
        echo " Service:     ${_SERVICE}"
        echo " Service URL: ${SERVICE_URL}"
        echo " Image:       ${IMAGE}"
        echo " API URL:     ${_API_URL}"
        echo " Compute URL: ${_COMPUTE_URL}"
        echo "--------------------------------------------------"

images:
  - "$_IMAGE"
