# Netlify configuration for GoldMIND AI (Vite frontend)

[build]
  # Build the app that lives in the monorepo subfolder
  base    = "frontend/web"
  command = "npm run build"
  publish = "dist"
  # (optional) Skip build if nothing in frontend/web changed:
  # ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF -- frontend/web"

[build.environment]
  NODE_VERSION  = "20"
  # Your frontend fetches use /api; Netlify proxies them to your Cloud Run API.
  VITE_API_BASE = "/api"

# ----- Redirects -----

# Proxy all frontend /api/* requests to your Cloud Run API service
[[redirects]]
  from   = "/api/*"
  to     = "https://api.fwvgoldmindai.com/:splat"
  status = 200
  force  = true

# SPA fallback so deep links like /dashboard load index.html
[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200

# ----- Headers -----

# Security headers for all routes
[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    X-Content-Type-Options    = "nosniff"
    X-Frame-Options           = "DENY"
    Referrer-Policy           = "no-referrer-when-downgrade"
    Permissions-Policy        = "camera=(), microphone=(), geolocation=()"

# Long-cache immutable assets generated by Vite
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Source maps (if you ship them): cache, but not forever
[[headers]]
  for = "/*.map"
  [headers.values]
    Cache-Control = "public, max-age=86400, must-revalidate"
