[build]
  publish = "public"
  command = ""

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "http://*"
  to   = "https://:splat"
  status = 301
  force  = true

[[redirects]]
  from = "/api/*"
  to   = "https://api.fwvgoldmindai.com/:splat"
  status = 200
  force  = true

[[redirects]]
  from = "/compute/*"
  to   = "https://goldmind-api-884387776097.us-central1.run.app/:splat"
  status = 200
  force  = true

[[redirects]]
  from = "/dashboard"
  to   = "/dashboard/"
  status = 301
