# .github/workflows/ci.yml
name: CI

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - "api/**"
      - "cloudbuild.yaml"
      - ".github/workflows/ci.yml"
  push:
    branches: [ "main" ]
    paths:
      - "api/**"
      - "cloudbuild.yaml"
      - ".github/workflows/ci.yml"

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Only run pytest if a tests folder (or *_test.py) exists.
      - name: Run tests if present
        shell: bash
        run: |
          if ls tests 1>/dev/null 2>&1 || ls *_test.py tests_*.py 1>/dev/null 2>&1; then
            pip install pytest
            pytest -q
          else
            echo "No tests found; skipping."
          fi
