name: Deploy to Cloud Run

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: deploy-main
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      GCP_REGION: ${{ secrets.GCP_REGION }}
      GCP_SERVICE: ${{ secrets.GCP_SERVICE }}
      # Optional runtime SA (NOT build SA)
      GCP_RUNTIME_SA: ${{ secrets.GCP_RUNTIME_SA }}

      # --- Tunables ---
      CLOUD_RUN_CPU: "1"           # 1 | 2 | 4
      CLOUD_RUN_MEMORY: "1Gi"      # 512Mi | 1Gi | 2Gi | ...
      CLOUD_RUN_CONCURRENCY: "80"  # requests per instance
      CLOUD_RUN_TIMEOUT: "60"      # seconds
      CLOUD_RUN_MIN_INSTANCES: "0" # set to 1+ to avoid cold start
      CLOUD_RUN_MAX_INSTANCES: "10"
      CLOUD_RUN_EXEC_ENV: "gen2"

    steps:
      - uses: actions/checkout@v4

      - name: Google Auth (JSON key)
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.GCP_PROJECT_ID }}
          export_default_credentials: true

      - name: Enable required APIs (idempotent)
        run: |
          gcloud services enable run.googleapis.com cloudbuild.googleapis.com artifactregistry.googleapis.com

      - name: Deploy to Cloud Run (build from source)
        run: |
          set -euo pipefail
          RUNTIME_FLAG=""
          if [[ -n "${GCP_RUNTIME_SA:-}" ]]; then
            RUNTIME_FLAG="--service-account=${GCP_RUNTIME_SA}"
          fi

          gcloud run deploy "${GCP_SERVICE}" \
            --project="${GCP_PROJECT_ID}" \
            --region="${GCP_REGION}" \
            --source="." \
            --allow-unauthenticated \
            --execution-environment="${CLOUD_RUN_EXEC_ENV}" \
            --cpu="${CLOUD_RUN_CPU}" \
            --memory="${CLOUD_RUN_MEMORY}" \
            --concurrency="${CLOUD_RUN_CONCURRENCY}" \
            --timeout="${CLOUD_RUN_TIMEOUT}" \
            --min-instances="${CLOUD_RUN_MIN_INSTANCES}" \
            --max-instances="${CLOUD_RUN_MAX_INSTANCES}" \
            ${RUNTIME_FLAG}

      - name: Smoke test
        run: |
          set -euo pipefail
          URL=$(gcloud run services describe "${GCP_SERVICE}" \
            --project="${GCP_PROJECT_ID}" --region="${GCP_REGION}" \
            --format='value(status.url)')
          echo "Service URL: $URL"
          curl -sSf "$URL/health" || (echo "Health check failed"; exit 1)
