name: Deploy to Cloud Run
on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    env:
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      GCP_REGION: ${{ secrets.GCP_REGION }}
      GCP_SERVICE: ${{ secrets.GCP_SERVICE }}
      CLOUD_RUN_DOMAIN: ${{ secrets.CLOUD_RUN_DOMAIN }}

    steps:
      - uses: actions/checkout@v4

      # Auth FIRST
      - name: Google Auth (JSON key)
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Verify auth
        run: |
          echo "Active account:"
          gcloud auth list --filter=status:ACTIVE --format='value(account)'
          gcloud config set project "$GCP_PROJECT_ID"

      # Compute which SA Cloud Build should use
      - name: Compute build service account
        id: buildsa
        run: |
          set -euo pipefail
          PRJNUM=$(gcloud projects describe "$GCP_PROJECT_ID" --format='value(projectNumber)')
          echo "BUILD_SA=${PRJNUM}@cloudbuild.gserviceaccount.com" >> "$GITHUB_OUTPUT"

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy "$GCP_SERVICE" \
            --source . \
            --region "$GCP_REGION" \
            --project "$GCP_PROJECT_ID" \
            --allow-unauthenticated \
            --build-service-account "${{ steps.buildsa.outputs.BUILD_SA }}"

      - name: Smoke test
        run: |
          set -euo pipefail
          URL="${CLOUD_RUN_DOMAIN:-}"
          if [ -z "$URL" ]; then
            URL="$(gcloud run services describe "$GCP_SERVICE" --region "$GCP_REGION" --format='value(status.url)')"
          fi
          echo "Testing $URL"
          (curl -fsS "$URL/health" || curl -fsS "$URL") >/dev/null
          echo "✅ Smoke test passed for $URL"
