# .github/workflows/auth-check.yml
name: Auth Check
on:
  workflow_dispatch: {}   # run it manually from the Actions tab

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Install gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Write key from secret and auth
        run: |
          set -euo pipefail
          printf '%s' '${{ secrets.GCP_SA_KEY }}' > $HOME/key.json
          python - <<'PY'
          import json, os
          print("client_email:", json.load(open(os.path.expanduser('~/key.json')))['client_email'])
          PY
          gcloud auth activate-service-account --key-file="$HOME/key.json"
          gcloud config set project "${{ secrets.GCP_PROJECT_ID }}"
          echo "Active account:"
          gcloud auth list --filter=status:ACTIVE --format="value(account)"
